services:
  # Backend Web Service
  - type: web
    name: devtrust-api
    env: node
    plan: free
    region: ohio
    buildCommand: npm install
    startCommand: npm start
    rootDirectory: server
    envVars:
      - key: NODE_VERSION
        value: 20
